### ISSUE TITLE
ModuleNotFoundError: No module named 'rest_meets_djongo'

### ISSUE THREAD

**Issue by MinaMeh** [SomeoneInParticular/rest_meets_djongo#5]
Hello,
I'm trying to work with rest_meets_djongo in my django rest api but I'm getting this error
`ModuleNotFoundError: No module named 'rest_meets_djongo'
`
any idea?

**Comment by SomeoneInParticular** [comment]
What version of Django/djongo/rest-meets-djongo are you using?

**Comment by MinaMeh** [comment]
Sorry I forgot to mention the versions:
rest-meets-djongo==0.0.13
djongo==1.3.0
Django==2.2.12
djangorestframework==3.11.0

**Comment by SomeoneInParticular** [comment]
Did you accidentally put 'rest-meets-djongo' into your INSTALLED_APPS settings list? That used to be a requirement, but no longer is

**Comment by MinaMeh** [comment]
No it is not, I tried to add it and I got same error, then I have removed it :disappointed:

**Comment by MinaMeh** [comment]
Well, my bad I had two sessions I installed the package in my venv but was launching the app outside.
Sorry again I'll close this issue

**Comment by SomeoneInParticular** [comment]
No problem! Glad its resolved
