### ISSUE TITLE
Error generating swagger documentation with DjongoModelSerializer

### ISSUE THREAD

**Issue by rnaranjo** [SomeoneInParticular/rest_meets_djongo#6]
I created a Serializer for a djongo model using DjongoModelSerializer as such:

```python
from app.models import Quotation
from rest_meets_djongo.serializers import DjongoModelSerializer
class QuotationSerializer(DjongoModelSerializer):
    class Meta:
        model = Quotation
        fields = ['id', 'step', 'answers', 'product', 'coverages', 'assistances', 'identity', 'created_on']
```

I'm using swagger to generate the documentation for my API (openapi), however after adding the DjongoModelSerializer class, whenever I try to access the documentation on my website I get a "Failed to load API definition" page with the following error on my server:

```sh
drf_yasg.errors.SwaggerGenerationError: Schema for <class rest_meets_djongo.serializers.DjongoModelSerializer.build_nested_embed_field.<locals>.EmbeddedSerializer'> would override distinct serializer <class 'rest_meets_djongo.serializers.DjongoModelSerializer.build_nested_embed_field.<locals>.EmbeddedSerializer'> because they implicitly share the same ref_name; explicitly set the ref_name atribute on both serializers' Meta classes
```

Any help on how to fix this issue?

**Comment by SomeoneInParticular** [comment]
Sorry for the delay; been getting prepped for school in September, and was quite busy.

I'm afraid I'm not very familiar with Swagger, so I'll have to do a bit more digging before I can really start debugging. In the meanwhile, could you show me your Quotation model schema (the EmbeddedFields, specifically)?
