### ISSUE TITLE
Updating supported versions of Django and Djongo

### ISSUE THREAD

**Issue by programmatix** [SomeoneInParticular/rest_meets_djongo#7]
Hi!  The pip package seems to be depending on older versions of Django (<3) and Djongo (<1.3.1):

```
$ pip3 install rest-meets-djongo
Collecting rest-meets-djongo
Collecting Django<3 (from rest-meets-djongo)
  Using cached https://files.pythonhosted.org/packages/6a/4c/4072f2f11c523898fb994874bbd1346d2e6c0b6968a2e1e87bee1c7a1729/Django-2.2.18-py3-none-any.whl
Collecting djongo<1.3.1,>=1.3.0 (from rest-meets-djongo)

```
Do you have any plans to upgrade support to the latest and greatest?

**Comment by SomeoneInParticular** [comment]
I do have plans to update, but its not a priority at the moment. I've become extremely busy of late (the joys of working with health care in current year), and most of the work I had managed to get done on this got wiped when my OS decided to become corrupted. From what I recall as well, the changes introduce by Django and Djongo required some pretty significant chunks of code to be entirely re-made, so its not a quick fix either (thankfully DRF didn't change too much though, or it'd probably need to remade from scratch). 

Djongo also lists explicit internal support for DRF coming soon(tm) as part of their planned enhancements, so they might actually beat me to the punch here as well. That is another reason this has been on the back-burner for so long, as the work required might end up entirely redundant at some point. Unless Nesdis himself decides that this package should become the "official" implementation, this will probably continue to be the case until more free time pops up.

Sorry for the inconvenience there; I hope this changes soon, but I just can't offer any guarantees or timelines right now.

**Comment by programmatix** [comment]
Ok, thank for you the response, and completely understood.  I can't offer to help alas, as I'm just a dabbler in all things Python.

**Comment by enver** [comment]
@SomeoneInParticular Could you investigate and prepare a plan, perhaps a community would like to jump in and help :)

**Comment by SomeoneInParticular** [comment]
So, I've come to the final decision regarding this repository.

I'm about to transition into a PhD program, and as a result will be far to busy to actively maintain the repository any longer (not that I really was for the last few months anyways). I also don't use Django anymore in any of my projects, so I don't have the expertise to translate the current code over with any sense of whats needed for it. For these reasons, and the reasons listed prior, I don't feel comfortable labeling this repository as still active.

As such, I've updated the README to state this clearly (which I will be pushing to pip shortly), and have opened the floor up for any other aspiring developers to work on and update the project as they see fit. My extreme apologies for the inconvenience, and I'm glad this package could be of use while I still had the time to maintain it. Hopefully someone with the time and expertise is able to bring the code up to speed with the new changes within Django and djongo.
